apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: exercicio1
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31111
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    appname: nginxserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
